title: kwohting # name of the site
author: kwohting # name of site's author
email: kwohting#gmail.com # email of site's author
url: https://kwohting.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
# description: > # description of the site (multiple lines allowed)
#   hello!

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)

# theme: no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
